// BEN Builder Academy - Course Curriculum
// All titles are original. Do not copy from external sources.

export const ACADEMY_COURSE = {
  title: "BEN Builder Academy",
  subtitle: "Full-Stack Web3 Development Program",
  description: "12 modules. 300+ lessons. Go from zero to shipping production web3 applications.",
  modules: [
    {
      id: 1,
      title: "Foundations",
      subtitle: "Dev setup, problem solving, Git workflow",
      icon: "terminal",
      lessonCount: 27,
      lessons: [
        { id: "1-1", title: "Welcome to the BEN Builder Academy" },
        { id: "1-2", title: "How Your Work Gets Evaluated" },
        { id: "1-3", title: "Module 1 Goals and Objectives" },
        { id: "1-4", title: "How Software Gets Built: The Development Lifecycle" },
        { id: "1-5", title: "Getting Started with Algorithms and Logical Thinking" },
        { id: "1-6", title: "Visualizing Logic with Flowcharts" },
        { id: "1-7", title: "Flowchart Hands-On Exercises" },
        { id: "1-8", title: "Writing Pseudocode Before Real Code" },
        { id: "1-9", title: "Pseudocode Hands-On Exercises" },
        { id: "1-10", title: "Getting Started with Linux" },
        { id: "1-11", title: "Running Linux in a Virtual Machine (Windows and Mac)" },
        { id: "1-12", title: "Navigating the Terminal: Core Linux Commands" },
        { id: "1-13", title: "Linux Command Line Exercises" },
        { id: "1-14", title: "Setting Up Your Code Editor (IDE)" },
        { id: "1-15", title: "Git and GitHub: The Big Picture" },
        { id: "1-16", title: "How Git Works Under the Hood" },
        { id: "1-17", title: "Essential Git Commands You Will Use Daily" },
        { id: "1-18", title: "Your First Steps with GitHub" },
        { id: "1-19", title: "Remote Repositories and Upstream Tracking" },
        { id: "1-20", title: "Branching Strategies in Git" },
        { id: "1-21", title: "Writing Good Markdown and README Files" },
        { id: "1-22", title: "A Real-World Git Workflow" },
        { id: "1-23", title: "Making Your GitHub Profile Stand Out" },
        { id: "1-24", title: "Collaboration Workflows on GitHub" },
        { id: "1-25", title: "Why Version Control Matters" },
        { id: "1-26", title: "Project Preview: Building a Task Manager App" },
        { id: "1-27", title: "Module 2 Goals and Objectives" },
      ],
    },
    {
      id: 2,
      title: "Web Fundamentals",
      subtitle: "HTML, CSS, core JavaScript",
      icon: "code",
      lessonCount: 24,
      lessons: [
        { id: "2-1", title: "Weekly Challenge: Build a Static Website with HTML and CSS" },
        { id: "2-2", title: "Your First Look at HTML and CSS" },
        { id: "2-3", title: "HTML Tags, Elements, and Practice" },
        { id: "2-4", title: "Deep Dive into HTML Structure" },
        { id: "2-5", title: "HTML Drills and Exercises" },
        { id: "2-6", title: "Styling Pages with CSS" },
        { id: "2-7", title: "CSS Drills and Exercises" },
        { id: "2-8", title: "Page Layouts with Flexbox and Grid" },
        { id: "2-9", title: "Layout Technique Exercises" },
        { id: "2-10", title: "Connecting Stylesheets to HTML Documents" },
        { id: "2-11", title: "JavaScript: The Language of the Web" },
        { id: "2-12", title: "Conditional Logic and Control Flow" },
        { id: "2-13", title: "Writing and Calling Functions in JS" },
        { id: "2-14", title: "Function Practice Problems" },
        { id: "2-15", title: "String Interpolation and Template Literals" },
        { id: "2-16", title: "Recursive Functions Explained" },
        { id: "2-17", title: "Recursion Practice Problems" },
        { id: "2-18", title: "Running JavaScript on Your Machine" },
        { id: "2-19", title: "Variables, Constants, and Scope" },
        { id: "2-20", title: "Primitive and Reference Data Types" },
        { id: "2-21", title: "Working with Arrays in JavaScript" },
        { id: "2-22", title: "Embedding JavaScript in an HTML Page" },
        { id: "2-23", title: "Loading External JavaScript Files" },
        { id: "2-24", title: "Building for Every Screen: Responsive Design" },
      ],
    },
    {
      id: 3,
      title: "Modern JavaScript",
      subtitle: "ES6+, OOP, async programming",
      icon: "zap",
      lessonCount: 41,
      lessons: [
        { id: "3-1", title: "Responsive Layouts with CSS Media Queries" },
        { id: "3-2", title: "Getting Started with Figma for Developers" },
        { id: "3-3", title: "Deploying a Static Site to Vercel" },
        { id: "3-4", title: "Assignment: Module 2 Project" },
        { id: "3-5", title: "Module 3 Goals and Objectives" },
        { id: "3-6", title: "Weekly Challenge: Programming Fundamentals in JS" },
        { id: "3-7", title: "Going Deeper with JavaScript" },
        { id: "3-8", title: "ECMAScript Standards and Versions" },
        { id: "3-9", title: "Check Your Knowledge: ECMAScript" },
        { id: "3-10", title: "Object-Oriented Programming Concepts" },
        { id: "3-11", title: "Creating and Using Objects in JS" },
        { id: "3-12", title: "Check Your Knowledge: OOP" },
        { id: "3-13", title: "Modern ES6 Syntax and Features" },
        { id: "3-14", title: "Building Your First JavaScript Class" },
        { id: "3-15", title: "Arrow Functions and Concise Syntax" },
        { id: "3-16", title: "Built-In JavaScript Methods" },
        { id: "3-17", title: "Check Your Knowledge: Object.assign() and Friends" },
        { id: "3-18", title: "Practice: Array Transformation Methods" },
        { id: "3-19", title: "Practice: Transforming Data with .map()" },
        { id: "3-20", title: "Practice: Selecting Data with .filter()" },
        { id: "3-21", title: "Practice: Accumulating Values with .reduce()" },
        { id: "3-22", title: "Unpacking Arrays with Destructuring" },
        { id: "3-23", title: "Practice: Using the Spread Operator" },
        { id: "3-24", title: "Leveling Up: Intermediate JavaScript" },
        { id: "3-25", title: "Making HTTP Requests with fetch()" },
        { id: "3-26", title: "ES6 Modules: Import and Export" },
        { id: "3-27", title: "Browser Storage: localStorage, sessionStorage, and Cache" },
        { id: "3-28", title: "Validating Forms on the Client Side" },
        { id: "3-29", title: "Async/Await: Writing Asynchronous Code That Reads Like Sync" },
        { id: "3-30", title: "Putting Async/Await into Practice" },
        { id: "3-31", title: "Check Your Knowledge: Async/Await" },
        { id: "3-32", title: "The Document Object Model (DOM) Explained" },
        { id: "3-33", title: "Check Your Knowledge: DOM Manipulation" },
        { id: "3-34", title: "Browser Storage and Cookies Deep Dive" },
        { id: "3-35", title: "Practice: Storage and Cookie Operations" },
        { id: "3-36", title: "HTTP Methods: GET and POST in Action" },
        { id: "3-37", title: "Handling Errors Gracefully with Try/Catch" },
        { id: "3-38", title: "Coding Exercise 1" },
        { id: "3-39", title: "Coding Exercise 2" },
        { id: "3-40", title: "Advanced JavaScript Patterns and Concepts" },
        { id: "3-41", title: "Webpack: Bundling Your Code for Production" },
      ],
    },
    {
      id: 4,
      title: "Server-Side Development",
      subtitle: "Node.js, Express, building APIs",
      icon: "server",
      lessonCount: 37,
      lessons: [
        { id: "4-1", title: "Dead Code Removal with Tree Shaking" },
        { id: "4-2", title: "Popular JavaScript Transpilers" },
        { id: "4-3", title: "TypeScript: Adding Types to JavaScript" },
        { id: "4-4", title: "Check Your Knowledge: TypeScript" },
        { id: "4-5", title: "JavaScript Promises from Scratch" },
        { id: "4-6", title: "Using Promises Inside Async Functions" },
        { id: "4-7", title: "Check Your Knowledge: Promises" },
        { id: "4-8", title: "Module Bundlers Explained" },
        { id: "4-9", title: "Transpiling and Polyfilling for Browser Support" },
        { id: "4-10", title: "Check Your Knowledge: Bundlers, Transpilers, Polyfills" },
        { id: "4-11", title: "Assignment: Module 3 Project" },
        { id: "4-12", title: "Module 4 Goals and Objectives" },
        { id: "4-13", title: "Weekly Challenge: Build a Backend with Node.js and Express" },
        { id: "4-14", title: "How Web Applications Work" },
        { id: "4-15", title: "The Server Side of Web Apps" },
        { id: "4-16", title: "Backend Frameworks: A Survey" },
        { id: "4-17", title: "Check Your Knowledge: Web Apps and Backends" },
        { id: "4-18", title: "Node.js: Server-Side JavaScript" },
        { id: "4-19", title: "How Clients Talk to Servers" },
        { id: "4-20", title: "The Request/Response Cycle" },
        { id: "4-21", title: "Managing Packages with npm" },
        { id: "4-22", title: "Browser JS vs. Node.js: Key Differences" },
        { id: "4-23", title: "Installing and Configuring Node.js" },
        { id: "4-24", title: "How Node.js Is Structured Internally" },
        { id: "4-25", title: "The Node.js Module System" },
        { id: "4-26", title: "Building Something Real with Node.js" },
        { id: "4-27", title: "Creating Your First Express Server" },
        { id: "4-28", title: "Working with Dynamic Data in Express" },
        { id: "4-29", title: "Hands-On: Node.js and Express Together" },
        { id: "4-30", title: "Check Your Knowledge: Express.js" },
        { id: "4-31", title: "Server-Side Templating Engines" },
        { id: "4-32", title: "Rendering HTML with Handlebars" },
        { id: "4-33", title: "Handlebars Hands-On Exercise" },
        { id: "4-34", title: "Check Your Knowledge: Handlebars" },
        { id: "4-35", title: "Rendering HTML with EJS" },
        { id: "4-36", title: "How Middleware Works in Express" },
        { id: "4-37", title: "Document Databases and NoSQL" },
      ],
    },
    {
      id: 5,
      title: "Backend Architecture",
      subtitle: "MVC patterns, middleware, API design",
      icon: "layers",
      lessonCount: 15,
      lessons: [
        { id: "5-1", title: "Building a NoSQL Backend with MongoDB" },
        { id: "5-2", title: "Designing RESTful APIs" },
        { id: "5-3", title: "Node.js: Wrapping Up and Review" },
        { id: "5-4", title: "Assignment: Module 4 Project" },
        { id: "5-5", title: "Module 5 Goals and Objectives" },
        { id: "5-6", title: "Weekly Challenge: Go Deeper with Express" },
        { id: "5-7", title: "Organizing Code with the MVC Pattern" },
        { id: "5-8", title: "Shipping Your Backend to Production" },
        { id: "5-9", title: "Middleware: How the Pipeline Really Works" },
        { id: "5-10", title: "Composing Multiple Middleware Functions" },
        { id: "5-11", title: "Check Your Knowledge: Middleware" },
        { id: "5-12", title: "Managing Config with Environment Variables and dotenv" },
        { id: "5-13", title: "Testing API Endpoints with Postman" },
        { id: "5-14", title: "Auth Testing and Authorization Flows in Postman" },
        { id: "5-15", title: "Assignment: Module 5 Project" },
      ],
    },
    {
      id: 6,
      title: "Data & Databases",
      subtitle: "PostgreSQL, SQL queries, migrations",
      icon: "database",
      lessonCount: 30,
      lessons: [
        { id: "6-1", title: "Module 6 Goals and Objectives" },
        { id: "6-2", title: "Weekly Challenge: Master Your Database Skills" },
        { id: "6-3", title: "Databases: Why They Exist and How They Work" },
        { id: "6-4", title: "Key-Value Stores Explained" },
        { id: "6-5", title: "Relational Database Management Systems (RDBMS)" },
        { id: "6-6", title: "Database Hosts, Ports, and Connections" },
        { id: "6-7", title: "Core Concepts of Relational Databases" },
        { id: "6-8", title: "Graph Databases and When to Use Them" },
        { id: "6-9", title: "Check Your Knowledge: Database Fundamentals" },
        { id: "6-10", title: "Getting Started with PostgreSQL" },
        { id: "6-11", title: "PostgreSQL Data Types" },
        { id: "6-12", title: "Check Your Knowledge: PostgreSQL" },
        { id: "6-13", title: "Writing Your First SQL Queries" },
        { id: "6-14", title: "Navigating the psql Interactive Console" },
        { id: "6-15", title: "Intermediate SQL: Beyond the Basics" },
        { id: "6-16", title: "Aggregating Rows with GROUP BY" },
        { id: "6-17", title: "Combining Tables with JOINs" },
        { id: "6-18", title: "Sorting Results with ORDER BY" },
        { id: "6-19", title: "Aggregate Functions: COUNT, SUM, AVG" },
        { id: "6-20", title: "Restricting Results with LIMIT" },
        { id: "6-21", title: "Database Migrations: What and Why" },
        { id: "6-22", title: "Running Migrations with SQL Files" },
        { id: "6-23", title: "Check Your Knowledge: Migrations" },
        { id: "6-24", title: "Keeping Databases Healthy and Secure" },
        { id: "6-25", title: "Backups, Dumps, and Scheduled Jobs" },
        { id: "6-26", title: "Check Your Knowledge: Database Backups" },
        { id: "6-27", title: "Guided Project: Build and Manage a PostgreSQL Database" },
        { id: "6-28", title: "Check Your Knowledge: Advanced Relational Concepts" },
        { id: "6-29", title: "Connecting a Node.js App to PostgreSQL with pg" },
        { id: "6-30", title: "Assignment: Module 6 Project" },
      ],
    },
    {
      id: 7,
      title: "Design & UI Engineering",
      subtitle: "Wireframing, Figma, responsive layouts",
      icon: "figma",
      lessonCount: 25,
      lessons: [
        { id: "7-1", title: "Module 7 Goals and Objectives" },
        { id: "7-2", title: "Weekly Challenge: Design Like a Pro" },
        { id: "7-3", title: "Wireframes, UI Kits, and Responsive Thinking" },
        { id: "7-4", title: "What Wireframing Actually Is" },
        { id: "7-5", title: "Designing with the User in Mind" },
        { id: "7-6", title: "Prebuilt UI Component Libraries" },
        { id: "7-7", title: "A Quick Tour of the Design Process" },
        { id: "7-8", title: "Frontend CSS Frameworks Overview" },
        { id: "7-9", title: "Building Fast with Bootstrap" },
        { id: "7-10", title: "Utility-First CSS with Tailwind" },
        { id: "7-11", title: "Where to Find Great Design Inspiration" },
        { id: "7-12", title: "Learning from Existing Web Designs" },
        { id: "7-13", title: "Top Sites and Tools for Design Reference" },
        { id: "7-14", title: "Turning Existing Designs into Wireframes" },
        { id: "7-15", title: "Building Wireframes and Mockups in Figma" },
        { id: "7-16", title: "Wireframing Resource Kit" },
        { id: "7-17", title: "Figma Wireframing Workshop" },
        { id: "7-18", title: "Wireframing Crash Course" },
        { id: "7-19", title: "Mobile-First and Responsive Design Principles" },
        { id: "7-20", title: "Responsive Design Approaches Compared" },
        { id: "7-21", title: "Responsive Design Recap" },
        { id: "7-22", title: "Loading Custom Fonts in Your Projects" },
        { id: "7-23", title: "Font Options Beyond Google Fonts" },
        { id: "7-24", title: "Using Icon Libraries in Your UI" },
        { id: "7-25", title: "Bringing It All Together: Full Design to Code" },
      ],
    },
    {
      id: 8,
      title: "React Development",
      subtitle: "Components, hooks, state management",
      icon: "component",
      lessonCount: 29,
      lessons: [
        { id: "8-1", title: "Assignment: Module 7 Project" },
        { id: "8-2", title: "Module 8 Goals and Objectives" },
        { id: "8-3", title: "Weekly Challenge: Build with React" },
        { id: "8-4", title: "Frontend Development in the Modern Era" },
        { id: "8-5", title: "Why React Exists and When to Use It" },
        { id: "8-6", title: "Core Features That Make React Powerful" },
        { id: "8-7", title: "How React Works Behind the Scenes" },
        { id: "8-8", title: "Thinking in Components" },
        { id: "8-9", title: "The Component Lifecycle: Mounting and Rendering" },
        { id: "8-10", title: "SSR vs. CSR: Server Rendering vs. Client Rendering" },
        { id: "8-11", title: "Single Page Applications and Client-Side Routing" },
        { id: "8-12", title: "Passing Data with Props and Managing State" },
        { id: "8-13", title: "How State Updates Trigger Re-renders" },
        { id: "8-14", title: "Writing JSX: HTML Inside JavaScript" },
        { id: "8-15", title: "Composition: Nesting Components with Children" },
        { id: "8-16", title: "Client-Side Navigation with React Router" },
        { id: "8-17", title: "Scaffolding a New React Project" },
        { id: "8-18", title: "Organizing Files and Folders in React" },
        { id: "8-19", title: "Rendering Dynamic Data in React" },
        { id: "8-20", title: "React Hooks: The Modern Way to Write Components" },
        { id: "8-21", title: "Managing Local State with useState" },
        { id: "8-22", title: "Running Side Effects with useEffect" },
        { id: "8-23", title: "Persisting Values with useRef and useMemo" },
        { id: "8-24", title: "Sharing Global State with useContext" },
        { id: "8-25", title: "React Hooks Practice Lab" },
        { id: "8-26", title: "Accessing DOM Nodes with Refs" },
        { id: "8-27", title: "Asset Bundling for React Apps" },
        { id: "8-28", title: "Global State Management with Redux" },
        { id: "8-29", title: "Build a Complete Task Manager in React" },
      ],
    },
    {
      id: 9,
      title: "Authentication & Security",
      subtitle: "OAuth, tokens, protected routes",
      icon: "shield",
      lessonCount: 43,
      lessons: [
        { id: "9-1", title: "Assignment: Module 8 Project" },
        { id: "9-2", title: "Module 9 Goals and Objectives" },
        { id: "9-3", title: "Weekly Challenge: Lock Down Your App" },
        { id: "9-4", title: "How Authentication and Encryption Work" },
        { id: "9-5", title: "Authentication vs. Authorization: Know the Difference" },
        { id: "9-6", title: "Common Ways to Authenticate Users" },
        { id: "9-7", title: "Authorization Frameworks Overview" },
        { id: "9-8", title: "Controlling Access by Role (RBAC)" },
        { id: "9-9", title: "Owner-Based Permissions (DAC)" },
        { id: "9-10", title: "Policy-Based Permissions (ABAC)" },
        { id: "9-11", title: "Where to Store Credentials Safely" },
        { id: "9-12", title: "Secrets Management for Applications" },
        { id: "9-13", title: "Using .env Files to Store Config" },
        { id: "9-14", title: "Auth Libraries for Node.js Applications" },
        { id: "9-15", title: "How JSON Web Tokens Work" },
        { id: "9-16", title: "Authentication Strategies with Passport.js" },
        { id: "9-17", title: "Token-Based Authentication Explained" },
        { id: "9-18", title: "Building a Basic Token Flow" },
        { id: "9-19", title: "Access Tokens and Refresh Tokens in Practice" },
        { id: "9-20", title: "OAuth and OpenID Connect Overview" },
        { id: "9-21", title: "OAuth in Detail" },
        { id: "9-22", title: "OpenID Connect in Detail" },
        { id: "9-23", title: "Implementing OAuth in a Web App" },
        { id: "9-24", title: "The OAuth Authorization Flow Step by Step" },
        { id: "9-25", title: "Sending Auth Data Between Client and Server" },
        { id: "9-26", title: "Reading and Writing Cookies" },
        { id: "9-27", title: "Parsing Cookies with Express Middleware" },
        { id: "9-28", title: "Making Cookies Secure" },
        { id: "9-29", title: "Cookie Security Flags Explained" },
        { id: "9-30", title: "Storing Data in localStorage" },
        { id: "9-31", title: "Using sessionStorage for Temporary Data" },
        { id: "9-32", title: "Advanced Session Storage Patterns" },
        { id: "9-33", title: "Encrypting Sensitive Data in Your App" },
        { id: "9-34", title: "Hashing Passwords with bcrypt" },
        { id: "9-35", title: "Guarding Routes from Unauthorized Users" },
        { id: "9-36", title: "JWT in Practice: Issuing and Verifying Tokens" },
        { id: "9-37", title: "Restricting Access Based on User Roles" },
        { id: "9-38", title: "Building Auth-Check Middleware" },
        { id: "9-39", title: "JWT Deep Dive: Advanced Patterns" },
        { id: "9-40", title: "Protected Routes: Advanced Implementation" },
        { id: "9-41", title: "Client vs. Server Route Protection" },
        { id: "9-42", title: "Locking Down REST API Endpoints" },
        { id: "9-43", title: "Route Guards in Express" },
      ],
    },
    {
      id: 10,
      title: "Testing & Quality",
      subtitle: "Unit testing, TDD, CI/CD",
      icon: "check-circle",
      lessonCount: 40,
      lessons: [
        { id: "10-1", title: "Guarding React Pages with Private Routes" },
        { id: "10-2", title: "Building a Private Route Component in React" },
        { id: "10-3", title: "Patterns for Protected Route Implementation" },
        { id: "10-4", title: "Wrapping Routes with Auth Checks" },
        { id: "10-5", title: "Sharing Auth State with React Context" },
        { id: "10-6", title: "Auth Best Practices Checklist" },
        { id: "10-7", title: "Authorization Best Practices Checklist" },
        { id: "10-8", title: "Assignment: Module 9 Project" },
        { id: "10-9", title: "Module 10 Goals and Objectives" },
        { id: "10-10", title: "Weekly Challenge: Write Bulletproof Tests" },
        { id: "10-11", title: "Why Testing Matters" },
        { id: "10-12", title: "The Different Kinds of Tests" },
        { id: "10-13", title: "Planning Your Test Strategy" },
        { id: "10-14", title: "Writing Your First Unit Tests" },
        { id: "10-15", title: "Organizing Test Files the Right Way" },
        { id: "10-16", title: "Choosing a Testing Framework" },
        { id: "10-17", title: "Popular Testing Frameworks Compared" },
        { id: "10-18", title: "All-Purpose Testing Libraries" },
        { id: "10-19", title: "Measuring How Much Code Your Tests Cover" },
        { id: "10-20", title: "Test-Driven Development (TDD) from Scratch" },
        { id: "10-21", title: "Behavior-Driven Development (BDD) Explained" },
        { id: "10-22", title: "TDD vs. BDD: When to Use Which" },
        { id: "10-23", title: "Writing Tests with Jest" },
        { id: "10-24", title: "Grouping Tests into Suites" },
        { id: "10-25", title: "Executing and Debugging Jest Tests" },
        { id: "10-26", title: "Generating Coverage Reports in Jest" },
        { id: "10-27", title: "Testing APIs: Tools and Techniques" },
        { id: "10-28", title: "API Testing Frameworks Compared" },
        { id: "10-29", title: "Mocking Dependencies in Your Tests" },
        { id: "10-30", title: "Mocks vs. Stubs: What is the Difference" },
        { id: "10-31", title: "Limitations and Tradeoffs of Mocking" },
        { id: "10-32", title: "When and How to Use Mocks Effectively" },
        { id: "10-33", title: "Faking API Responses in Tests" },
        { id: "10-34", title: "Test Fixtures: Setting Up Reusable Data" },
        { id: "10-35", title: "Practical Testing Examples" },
        { id: "10-36", title: "Automating Browser Tests" },
        { id: "10-37", title: "Headless Browser Testing Tools" },
        { id: "10-38", title: "Testing React Components in Isolation" },
        { id: "10-39", title: "Integration Tests: Making Sure Parts Work Together" },
        { id: "10-40", title: "End-to-End Tests: Simulating Real User Flows" },
      ],
    },
    {
      id: 11,
      title: "Deployment & Infrastructure",
      subtitle: "Cloud hosting, containers, SSL",
      icon: "cloud",
      lessonCount: 35,
      lessons: [
        { id: "11-1", title: "Connecting Tests to Your CI/CD Pipeline" },
        { id: "11-2", title: "Configuring Continuous Integration for Your Project" },
        { id: "11-3", title: "Running CI Workflows with GitHub Actions" },
        { id: "11-4", title: "Advanced Testing Topics" },
        { id: "11-5", title: "Assignment: Module 10 Project" },
        { id: "11-6", title: "Module 11 Goals and Objectives" },
        { id: "11-7", title: "Weekly Challenge: Ship Your App to the Cloud" },
        { id: "11-8", title: "Cloud Platforms and Hosting Options" },
        { id: "11-9", title: "DevOps Fundamentals for Developers" },
        { id: "11-10", title: "Understanding Deployment Environments" },
        { id: "11-11", title: "The Testing Environment" },
        { id: "11-12", title: "The Staging Environment" },
        { id: "11-13", title: "The Production Environment" },
        { id: "11-14", title: "Security Considerations for Each Environment" },
        { id: "11-15", title: "Deciding Which Environments You Need" },
        { id: "11-16", title: "Setting Up Your Local Dev Environment" },
        { id: "11-17", title: "Hosting Vocabulary: Terms You Need to Know" },
        { id: "11-18", title: "Choosing a Hosting Provider" },
        { id: "11-19", title: "Running Apps in Containers (Docker)" },
        { id: "11-20", title: "Comparing Deployment Strategies" },
        { id: "11-21", title: "Deploying to a Platform-as-a-Service (PaaS)" },
        { id: "11-22", title: "Deploying to a Virtual Private Server (VPS)" },
        { id: "11-23", title: "Going Serverless: Functions in the Cloud" },
        { id: "11-24", title: "Hosting Your Database in Production" },
        { id: "11-25", title: "Managed Database Services" },
        { id: "11-26", title: "Running Your Own Database Server" },
        { id: "11-27", title: "Managing Env Vars and Secrets in Production" },
        { id: "11-28", title: "Setting Env Vars on Heroku" },
        { id: "11-29", title: "Setting Env Vars on Vercel" },
        { id: "11-30", title: "Setting Env Vars on an AWS VPS" },
        { id: "11-31", title: "Web Servers and Reverse Proxies (Nginx)" },
        { id: "11-32", title: "Custom Domains and SSL/TLS Basics" },
        { id: "11-33", title: "How SSL Certificates Work" },
        { id: "11-34", title: "Free SSL with Let's Encrypt and Nginx" },
        { id: "11-35", title: "How Certificate Verification Actually Works" },
      ],
    },
    {
      id: 12,
      title: "Launch & Ship",
      subtitle: "Project management, pitching, startup building",
      icon: "rocket",
      lessonCount: 47,
      lessons: [
        { id: "12-1", title: "Getting an SSL Certificate for Your App" },
        { id: "12-2", title: "Walkthrough: Generating Certs with Certbot" },
        { id: "12-3", title: "Case Study: Deploying to PaaS (Vercel/Heroku)" },
        { id: "12-4", title: "Case Study: Deploying to a VPS on AWS" },
        { id: "12-5", title: "Advanced Deployment Topics" },
        { id: "12-6", title: "Assignment: Module 11 Project" },
        { id: "12-7", title: "Module 12 Goals and Objectives" },
        { id: "12-8", title: "Project Management for Developers" },
        { id: "12-9", title: "Organizing Work with Kanban Boards" },
        { id: "12-10", title: "Software Development Methodologies Overview" },
        { id: "12-11", title: "The Phases of Building Software" },
        { id: "12-12", title: "Agile vs. Waterfall: Choosing Your Approach" },
        { id: "12-13", title: "How Scrum Works in Practice" },
        { id: "12-14", title: "Planning and Running Dev Sprints" },
        { id: "12-15", title: "Monitoring Your Progress" },
        { id: "12-16", title: "Tracking Bugs and Features with Issues" },
        { id: "12-17", title: "GitHub Issues as a Project Management Tool" },
        { id: "12-18", title: "Collaborating with a Project Manager" },
        { id: "12-19", title: "Entrepreneurship for Developers" },
        { id: "12-20", title: "Founder vs. Employee: Choosing Your Path" },
        { id: "12-21", title: "How to Launch a Startup" },
        { id: "12-22", title: "Developing a Builder's Mindset" },
        { id: "12-23", title: "Building a Startup While Keeping Your Day Job" },
        { id: "12-24", title: "Stress-Testing Your Startup Idea" },
        { id: "12-25", title: "Building a Personal Knowledge System" },
        { id: "12-26", title: "Capturing and Organizing Ideas" },
        { id: "12-27", title: "The PARA Method for Information Management" },
        { id: "12-28", title: "Turning Rough Ideas into Real Projects" },
        { id: "12-29", title: "What Makes an Idea Marketable" },
        { id: "12-30", title: "Finding Problems Worth Solving" },
        { id: "12-31", title: "Spotting Opportunities in the Market" },
        { id: "12-32", title: "Defining and Reaching Your Target Audience" },
        { id: "12-33", title: "MVPs and Pre-Launch Landing Pages" },
        { id: "12-34", title: "Building a Pre-Launch Signup Page" },
        { id: "12-35", title: "Pitch Decks: Why They Matter" },
        { id: "12-36", title: "Anatomy of a Winning Pitch Deck" },
        { id: "12-37", title: "Presenting Your Idea with Confidence" },
        { id: "12-38", title: "User Personas and User Stories" },
        { id: "12-39", title: "Delivering a Pitch That Lands" },
        { id: "12-40", title: "Fundraising 101: How Startup Investment Works" },
        { id: "12-41", title: "How Funding Rounds Work" },
        { id: "12-42", title: "Choosing a Revenue Model" },
        { id: "12-43", title: "Sprint Planning for Your Capstone" },
        { id: "12-44", title: "Getting the Word Out: Marketing for Builders" },
        { id: "12-45", title: "Closing Your First Sale" },
        { id: "12-46", title: "Building Your Capstone Project" },
        { id: "12-47", title: "Assignment: Module 12 Final Project" },
      ],
    },
  ],
};
