/**
 * Curated crypto conferences & side events.
 * Updated: 2026-03-13
 *
 * status: "past" | "upcoming" | "happening"
 * tier: "flagship" | "major" | "regional" | "hackathon"
 */

export const CONFERENCES = [
  // ─── APRIL 2026 ──────────────────────────────────────
  {
    id: "ethglobal-cannes-2026",
    name: "ETHGlobal Cannes",
    tier: "hackathon",
    dates: "Apr 3-5, 2026",
    startDate: "2026-04-03",
    endDate: "2026-04-05",
    location: "Cannes, France",
    flag: "🇫🇷",
    venue: null,
    description: "In-person ETHGlobal hackathon on the French Riviera. Part of ETHGlobal's worldwide hackathon circuit for Ethereum builders.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.b-cdn.net/events/cannes/images/bd4oc/default.jpg",
    attendees: "1,500+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "builders"],
    cryptoWeek: null,
    sideEvents: [],
  },
  {
    id: "paris-blockchain-week-2026",
    name: "Paris Blockchain Week",
    tier: "flagship",
    dates: "Apr 15-16, 2026",
    startDate: "2026-04-15",
    endDate: "2026-04-16",
    location: "Paris, France",
    flag: "🇫🇷",
    venue: "Carrousel du Louvre",
    description: "The bridge between TradFi and digital assets. 320+ C-suite speakers, heavy institutional focus. VIP dinner at the Chateau de Versailles.",
    url: "https://www.parisblockchainweek.com",
    ticketUrl: "https://www.parisblockchainweek.com/tickets",
    coverImage: "https://cdn.prod.website-files.com/68eca791adb89a162563dcd8/68ef6daccab37aff4baaf73b_PBW25-poster-00001.jpg",
    attendees: "10,000+",
    priceRange: "$$",
    tags: ["institutional", "tradfi", "europe"],
    cryptoWeek: "Paris Crypto Week",
    sideEvents: [
      { name: "VIP Dinner at Versailles", type: "networking" },
      { name: "Institutional Summit", type: "conference" },
      { name: "Paris Blockchain Week Hackathon", type: "hackathon" },
      { name: "Startup Competition", type: "pitch" },
    ],
  },
  {
    id: "bitcoin-2026",
    name: "Bitcoin 2026",
    tier: "flagship",
    dates: "Apr 27-29, 2026",
    startDate: "2026-04-27",
    endDate: "2026-04-29",
    location: "Las Vegas, USA",
    flag: "🇺🇸",
    venue: "The Venetian Resort & Expo",
    description: "The world's largest Bitcoin conference. 40,000+ attendees, 500+ speakers. Past speakers include Trump, Snowden, and Jack Dorsey.",
    url: "https://2026.b.tc/",
    ticketUrl: "https://tickets.b.tc/event/bitcoin-2026/tickets",
    coverImage: "https://cdn.prod.website-files.com/68ffb1590591ad046ce9ac85/6932fe6bc061484763949ae4_btc-b26-bg-image.webp",
    attendees: "40,000+",
    priceRange: "$449 - $9,499",
    tags: ["bitcoin", "flagship", "usa"],
    cryptoWeek: "Bitcoin Week Las Vegas",
    sideEvents: [
      { name: "Pro Day", type: "conference" },
      { name: "Women of Bitcoin Bash", type: "networking" },
      { name: "Deal Day", type: "networking" },
      { name: "Compute Village", type: "expo" },
      { name: "Open Source Stage", type: "conference" },
    ],
    speakers: ["Michael Saylor", "SEC Chair Paul Atkins", "Sen. Cynthia Lummis"],
  },
  {
    id: "token2049-dubai-2026",
    name: "Token2049 Dubai",
    tier: "flagship",
    dates: "Apr 29-30, 2026",
    startDate: "2026-04-29",
    endDate: "2026-04-30",
    location: "Dubai, UAE",
    flag: "🇦🇪",
    venue: "Madinat Jumeirah",
    description: "The premier crypto event in the Middle East. Luxury resort setting with 70%+ C-level attendance from 160+ countries.",
    url: "https://token2049.com/dubai",
    ticketUrl: "https://token2049.com/dubai",
    coverImage: "https://cdn.prod.website-files.com/6756df8f05088bc3e51c64c0/698095fc4e4b28f77296b5fd_homepage-hero-posterimage.avif",
    attendees: "15,000+",
    priceRange: "$$$",
    tags: ["institutional", "networking", "middle-east"],
    cryptoWeek: "Dubai Crypto Week",
    sideEvents: [
      { name: "500+ side events across Dubai", type: "networking" },
    ],
    speakers: ["Pavel Durov", "Balaji Srinivasan", "Paolo Ardoino"],
  },

  // ─── MAY 2026 ────────────────────────────────────────
  {
    id: "consensus-2026",
    name: "Consensus 2026",
    tier: "flagship",
    dates: "May 5-7, 2026",
    startDate: "2026-05-05",
    endDate: "2026-05-07",
    location: "Miami Beach, USA",
    flag: "🇺🇸",
    venue: "Miami Beach Convention Center",
    description: "CoinDesk's flagship event. The longest-running major crypto conference where crypto, capital, and culture converge. $4 trillion AUM represented.",
    url: "https://consensus.coindesk.com/",
    ticketUrl: "https://consensus.coindesk.com/",
    coverImage: "https://d2pasa6bkzkrjd.cloudfront.net/site/consensus2026/images/userfiles/home/lead-space-c26/Consensus-2026-Website Leadspace_Desktop.jpg",
    attendees: "20,000+",
    priceRange: "$$$",
    tags: ["flagship", "institutional", "usa"],
    cryptoWeek: "Miami Crypto Week",
    sideEvents: [
      { name: "CoinDesk PitchFest", type: "pitch" },
      { name: "Consensus Hackathon", type: "hackathon" },
      { name: "Solana Accelerate", type: "conference" },
      { name: "Wealth Management Day", type: "conference" },
      { name: "Miami side events & pool parties", type: "networking" },
    ],
    speakers: ["Mike Novogratz", "Arthur Hayes", "Sergey Nazarov", "Brad Garlinghouse"],
  },

  // ─── MAY-JUNE 2026 ──────────────────────────────────
  {
    id: "das-2026",
    name: "DAS 2026 (Digital Asset Summit)",
    tier: "major",
    dates: "May 19-21, 2026",
    startDate: "2026-05-19",
    endDate: "2026-05-21",
    location: "New York City, USA",
    flag: "🇺🇸",
    venue: null,
    description: "Blockworks' flagship institutional summit. Where TradFi meets DeFi. Deep-dive panels on macro, institutional adoption, and market structure.",
    url: "https://blockworks.co/DAS",
    ticketUrl: "https://blockworks.co/DAS",
    coverImage: "https://blockworks-co.imgix.net/wp-content/uploads/2025/09/DASNY2026_Background_20251016c.jpg",
    attendees: "5,000+",
    priceRange: "$$$",
    tags: ["institutional", "tradfi", "usa"],
    cryptoWeek: null,
    sideEvents: [],
  },
  {
    id: "ethglobal-prague-2026",
    name: "ETHGlobal Prague",
    tier: "hackathon",
    dates: "May 29-31, 2026",
    startDate: "2026-05-29",
    endDate: "2026-05-31",
    location: "Prague, Czech Republic",
    flag: "🇨🇿",
    venue: null,
    description: "In-person ETHGlobal hackathon in Prague. Part of ETHGlobal's worldwide hackathon circuit.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.b-cdn.net/events/prague/images/gq2mh/default.jpg",
    attendees: "1,500+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "europe"],
    cryptoWeek: null,
    sideEvents: [],
  },

  // ─── JUNE 2026 ───────────────────────────────────────
  {
    id: "ethconf-2026",
    name: "ETHConf",
    tier: "major",
    dates: "Jun 8-10, 2026",
    startDate: "2026-06-08",
    endDate: "2026-06-10",
    location: "New York City, USA",
    flag: "🇺🇸",
    venue: null,
    description: "ETHGlobal's conference format event. Application-based. Immediately followed by ETHGlobal NYC hackathon, creating Ethereum Week NYC.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.com/og.png",
    attendees: "3,000+",
    priceRange: "Application-based",
    tags: ["ethereum", "builders", "usa"],
    cryptoWeek: "Ethereum Week NYC",
    sideEvents: [],
  },
  {
    id: "ethglobal-nyc-2026",
    name: "ETHGlobal New York",
    tier: "hackathon",
    dates: "Jun 12-14, 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    location: "New York City, USA",
    flag: "🇺🇸",
    venue: null,
    description: "In-person hackathon immediately following ETHConf. Part of Ethereum Week NYC.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.b0bd725bc77a3ea7cd3826627d01fcb6.r2.cloudflarestorage.com/events/jsp32/banner/1764002430828_Hackathon%20Banner-New%20York.jpg",
    attendees: "2,000+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "builders"],
    cryptoWeek: "Ethereum Week NYC",
    sideEvents: [],
  },

  // ─── JULY 2026 ───────────────────────────────────────
  {
    id: "ethglobal-lisbon-2026",
    name: "ETHGlobal Lisbon",
    tier: "hackathon",
    dates: "Jul 24-26, 2026",
    startDate: "2026-07-24",
    endDate: "2026-07-26",
    location: "Lisbon, Portugal",
    flag: "🇵🇹",
    venue: null,
    description: "In-person ETHGlobal hackathon in Lisbon. Part of the worldwide hackathon circuit.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.com/og.png",
    attendees: "1,500+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "europe"],
    cryptoWeek: null,
    sideEvents: [],
  },

  // ─── AUGUST 2026 ─────────────────────────────────────
  {
    id: "bitcoin-hong-kong-2026",
    name: "Bitcoin Hong Kong",
    tier: "regional",
    dates: "Aug 27-28, 2026",
    startDate: "2026-08-27",
    endDate: "2026-08-28",
    location: "Hong Kong",
    flag: "🇭🇰",
    venue: "Hong Kong Convention and Exhibition Centre",
    description: "Bitcoin Magazine's Asia edition. Focused on builders and investors across the Asian Bitcoin ecosystem.",
    url: "https://asia.b.tc/2026",
    ticketUrl: "https://tickets.b.tc/event/bitcoin-hong-kong-2026/tickets",
    coverImage: "https://cdn.prod.website-files.com/68fbd2322c5cffba97028abd/692ec40531c5fc33cd8f09c5_OG-Image.jpg",
    attendees: "5,000+",
    priceRange: "$48 - $2,288",
    tags: ["bitcoin", "asia"],
    cryptoWeek: null,
    sideEvents: [],
    speakers: ["Michael Saylor", "CZ"],
  },

  // ─── SEPTEMBER 2026 ──────────────────────────────────
  {
    id: "nft-nyc-2026",
    name: "NFT.NYC",
    tier: "major",
    dates: "Sep 1-3, 2026",
    startDate: "2026-09-01",
    endDate: "2026-09-03",
    location: "New York City, USA",
    flag: "🇺🇸",
    venue: "Marriott Marquis, Times Square",
    description: "Builders, brands, and creators shaping the future of digital ownership. Rebranded beyond just NFTs.",
    url: "https://www.nft.nyc",
    ticketUrl: "https://www.nft.nyc",
    coverImage: "https://www.nft.nyc/hubfs/nftnyc2021-eventbrite-header.png",
    attendees: "5,000+",
    priceRange: "$$",
    tags: ["nft", "culture", "usa"],
    cryptoWeek: null,
    sideEvents: [],
  },
  {
    id: "ethglobal-tokyo-2026",
    name: "ETHGlobal Tokyo",
    tier: "hackathon",
    dates: "Sep 25-27, 2026",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    location: "Tokyo, Japan",
    flag: "🇯🇵",
    venue: null,
    description: "In-person ETHGlobal hackathon in Tokyo.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.com/og.png",
    attendees: "1,500+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "asia"],
    cryptoWeek: null,
    sideEvents: [],
  },
  {
    id: "korea-blockchain-week-2026",
    name: "Korea Blockchain Week",
    tier: "major",
    dates: "Sep 29 - Oct 1, 2026",
    startDate: "2026-09-29",
    endDate: "2026-10-01",
    location: "Seoul, South Korea",
    flag: "🇰🇷",
    venue: null,
    description: "Asia's premier blockchain event. Seoul becomes a crypto hub for the week with dozens of satellite events.",
    url: "https://koreablockchainweek.com",
    ticketUrl: "https://koreablockchainweek.com",
    coverImage: "https://framerusercontent.com/images/Hoz1f8pTtWgU6W04EICXaDmayI.png",
    attendees: "8,000+",
    priceRange: "$$",
    tags: ["asia", "institutional", "builders"],
    cryptoWeek: "Seoul Crypto Week",
    sideEvents: [],
  },

  // ─── OCTOBER 2026 ────────────────────────────────────
  {
    id: "token2049-singapore-2026",
    name: "Token2049 Singapore",
    tier: "flagship",
    dates: "Oct 7-8, 2026",
    startDate: "2026-10-07",
    endDate: "2026-10-08",
    location: "Singapore",
    flag: "🇸🇬",
    venue: "Marina Bay Sands",
    description: "The world's largest crypto event. All 5 floors of Marina Bay Sands. 25,000+ attendees, 7,000+ companies, 300+ speakers from 160+ countries.",
    url: "https://token2049.com/singapore",
    ticketUrl: "https://token2049.com/singapore",
    coverImage: "https://cdn.prod.website-files.com/6756df8f05088bc3e51c64c0/68d16021e76fc9c73527ae08_audience.avif",
    attendees: "25,000+",
    priceRange: "$$$",
    tags: ["flagship", "institutional", "asia"],
    cryptoWeek: "Singapore Crypto Week",
    sideEvents: [
      { name: "Origins Hackathon (36hr)", type: "hackathon" },
      { name: "NEXUS Startup Competition", type: "pitch" },
      { name: "AFTER 2049 (MBS SkyPark)", type: "networking" },
      { name: "700+ side events across Singapore", type: "networking" },
    ],
  },

  // ─── NOVEMBER 2026 ───────────────────────────────────
  {
    id: "devcon-8-2026",
    name: "Devcon 8",
    tier: "flagship",
    dates: "Nov 3-6, 2026",
    startDate: "2026-11-03",
    endDate: "2026-11-06",
    location: "Mumbai, India",
    flag: "🇮🇳",
    venue: "Jio World Centre",
    description: "The Ethereum Foundation's flagship developer conference. Technical talks, workshops, Community Hubs. India chosen for its fast-growing Ethereum developer community.",
    url: "https://devcon.org",
    ticketUrl: "https://devcon.org",
    coverImage: "https://devcon.org/_next/static/media/devcon-india-banner.b4aeef51.png",
    attendees: "12,000+",
    priceRange: "Application-based",
    tags: ["ethereum", "builders", "flagship"],
    cryptoWeek: "Devcon Week Mumbai",
    sideEvents: [
      { name: "ETHGlobal Mumbai (Nov 6-8)", type: "hackathon" },
      { name: "Community Hubs", type: "community" },
      { name: "Devcon Week side events", type: "networking" },
    ],
  },
  {
    id: "ethglobal-mumbai-2026",
    name: "ETHGlobal Mumbai",
    tier: "hackathon",
    dates: "Nov 6-8, 2026",
    startDate: "2026-11-06",
    endDate: "2026-11-08",
    location: "Mumbai, India",
    flag: "🇮🇳",
    venue: null,
    description: "In-person ETHGlobal hackathon immediately following Devcon 8. Part of Devcon Week Mumbai.",
    url: "https://ethglobal.com/events",
    ticketUrl: "https://ethglobal.com/events",
    coverImage: "https://ethglobal.com/og.png",
    attendees: "2,000+",
    priceRange: "Free",
    tags: ["ethereum", "hackathon", "asia"],
    cryptoWeek: "Devcon Week Mumbai",
    sideEvents: [],
  },
  {
    id: "bitcoin-amsterdam-2026",
    name: "Bitcoin Amsterdam",
    tier: "regional",
    dates: "Nov 5-6, 2026",
    startDate: "2026-11-05",
    endDate: "2026-11-06",
    location: "Amsterdam, Netherlands",
    flag: "🇳🇱",
    venue: "Sugar Factory, Halfweg",
    description: "Europe's leading Bitcoin conference. Two days of keynotes, panels, and networking. 5% discount for Bitcoin payments.",
    url: "https://www.bitcoin.amsterdam/2026",
    ticketUrl: "https://www.bitcoin.amsterdam/tickets",
    coverImage: "https://cdn.prod.website-files.com/68b7325012d13955383b007f/68b99602952cbdd5f479f243_btc-amsterdam-homepage-treasury-announcement.webp",
    attendees: "3,000+",
    priceRange: "€121 - €1,410",
    tags: ["bitcoin", "europe"],
    cryptoWeek: null,
    sideEvents: [
      { name: "Whale Night", type: "networking" },
    ],
  },
  {
    id: "web-summit-2026",
    name: "Web Summit",
    tier: "major",
    dates: "Nov 9-12, 2026",
    startDate: "2026-11-09",
    endDate: "2026-11-12",
    location: "Lisbon, Portugal",
    flag: "🇵🇹",
    venue: "MEO Arena",
    description: "The world's largest technology conference. 70,000+ attendees across 20 content tracks including dedicated Web3 and crypto stages.",
    url: "https://websummit.com",
    ticketUrl: "https://websummit.com",
    coverImage: "https://websummit.com/wp-media/2025/11/lis26-wrap-thumbnail-aspect-ratio-1568-788.jpg",
    attendees: "70,000+",
    priceRange: "$$",
    tags: ["tech", "web3", "europe"],
    cryptoWeek: null,
    sideEvents: [],
  },
  {
    id: "solana-breakpoint-2026",
    name: "Solana Breakpoint",
    tier: "flagship",
    dates: "Nov 15-17, 2026",
    startDate: "2026-11-15",
    endDate: "2026-11-17",
    location: "London, England",
    flag: "🇬🇧",
    venue: "Olympia London",
    description: "Solana's flagship annual conference for founders, developers, and creators. Moving to London for 2026.",
    url: "https://solana.com/breakpoint",
    ticketUrl: "https://solana.com/breakpoint",
    coverImage: "https://solana.com/breakpoint/twitter-card.v2.jpg",
    attendees: "5,000+",
    priceRange: "$300 - $500",
    tags: ["solana", "builders", "flagship"],
    cryptoWeek: "Solana London Week",
    sideEvents: [],
  },

  // ─── DECEMBER 2026 ───────────────────────────────────
  {
    id: "bitcoin-mena-2026",
    name: "Bitcoin MENA",
    tier: "regional",
    dates: "Dec 2026",
    startDate: "2026-12-01",
    endDate: "2026-12-02",
    location: "Abu Dhabi, UAE",
    flag: "🇦🇪",
    venue: "ADNEC Centre",
    description: "Premier Bitcoin conference for the Middle East and North Africa region.",
    url: "https://mena.b.tc/",
    ticketUrl: "https://tickets.b.tc/event/bitcoin-mena-2026/tickets",
    coverImage: "https://cdn.prod.website-files.com/687f979126432c8ce843e6cd/6931b4e73c030b2e09ea2105_MENA%20Homepage%20for%202026%201920x1080.png",
    attendees: "5,000+",
    priceRange: "$21 - $2,999",
    tags: ["bitcoin", "middle-east"],
    cryptoWeek: null,
    sideEvents: [],
  },
];

// ─── CRYPTO WEEKS (conference seasons) ─────────────────
export const CRYPTO_WEEKS = [
  { name: "Paris Crypto Week", when: "Mid-April", anchor: "Paris Blockchain Week", location: "Paris" },
  { name: "Bitcoin Week Las Vegas", when: "Late April", anchor: "Bitcoin 2026", location: "Las Vegas" },
  { name: "Dubai Crypto Week", when: "Late April", anchor: "Token2049 Dubai", location: "Dubai" },
  { name: "Miami Crypto Week", when: "Early May", anchor: "Consensus 2026", location: "Miami" },
  { name: "Ethereum Week NYC", when: "Mid-June", anchor: "ETHConf + ETHGlobal NYC", location: "New York" },
  { name: "Seoul Crypto Week", when: "Late September", anchor: "Korea Blockchain Week", location: "Seoul" },
  { name: "Singapore Crypto Week", when: "Early October", anchor: "Token2049 Singapore", location: "Singapore" },
  { name: "Devcon Week Mumbai", when: "Early November", anchor: "Devcon 8 + ETHGlobal Mumbai", location: "Mumbai" },
  { name: "Solana London Week", when: "Mid-November", anchor: "Solana Breakpoint", location: "London" },
];

// Helper: determine status based on current date
export function getEventStatus(conf) {
  const now = new Date().toISOString().split("T")[0];
  if (now > conf.endDate) return "past";
  if (now >= conf.startDate && now <= conf.endDate) return "happening";
  return "upcoming";
}

// Tier display config
export const TIER_CONFIG = {
  flagship: { label: "Flagship", color: "#FF872A" },
  major: { label: "Major", color: "#6366f1" },
  regional: { label: "Regional", color: "#10b981" },
  hackathon: { label: "Hackathon", color: "#8b5cf6" },
  community: { label: "Community", color: "#06b6d4" },
  conference: { label: "Conference", color: "#6366f1" },
  "side-event": { label: "Side Event", color: "#f59e0b" },
};
