// BEN Solidity Engineering Program - Course Curriculum
// All titles are original. Do not copy from external sources.

export const SOLIDITY_COURSE = {
  title: "BEN Solidity Program",
  subtitle: "Advanced Smart Contract Engineering",
  description: "16 modules. 200+ lessons. Go from writing your first contract to auditing production protocols.",
  modules: [
    {
      id: 1,
      title: "Ethereum & Cryptography Foundations",
      subtitle: "How blockchains work, hashing, signatures, consensus",
      icon: "lock",
      lessons: [
        { id: "1-1", title: "Program Orientation and What to Expect" },
        { id: "1-2", title: "Cryptographic Hash Functions and Their Role in Blockchains" },
        { id: "1-3", title: "Public Key Cryptography and Digital Signatures" },
        { id: "1-4", title: "How Ethereum Processes Transactions" },
        { id: "1-5", title: "Merkle Trees and State Verification" },
        { id: "1-6", title: "Consensus Mechanisms: Proof of Work vs. Proof of Stake" },
        { id: "1-7", title: "The Ethereum Virtual Machine from the Ground Up" },
        { id: "1-8", title: "Accounts, Nonces, and the Global State Trie" },
        { id: "1-9", title: "Gas, Base Fees, and EIP-1559 Fee Mechanics" },
        { id: "1-10", title: "Writing and Deploying Your First Solidity Contract" },
        { id: "1-11", title: "Implementing a Basic ERC-20 Token from Scratch" },
        { id: "1-12", title: "Adding Non-Standard Features to Your Token" },
        { id: "1-13", title: "Assignment: Build a Custom Token with Transfer Rules" },
      ],
    },
    {
      id: 2,
      title: "Solidity Deep Dive",
      subtitle: "Types, storage layout, modifiers, error handling",
      icon: "code",
      lessons: [
        { id: "2-1", title: "Value Types, Reference Types, and Type Casting" },
        { id: "2-2", title: "Function Visibility and Access Patterns" },
        { id: "2-3", title: "Custom Modifiers for Reusable Guard Logic" },
        { id: "2-4", title: "Error Handling: require, revert, and Custom Errors" },
        { id: "2-5", title: "Mappings, Nested Mappings, and Iterable Patterns" },
        { id: "2-6", title: "Memory vs. Storage vs. Calldata" },
        { id: "2-7", title: "Structs, Arrays, and Packed Storage Slots" },
        { id: "2-8", title: "Events, Logs, and Indexed Parameters" },
        { id: "2-9", title: "Inheritance, Interfaces, and Abstract Contracts" },
        { id: "2-10", title: "Libraries and the delegatecall Pattern" },
        { id: "2-11", title: "Setting Up Hardhat for Local Development" },
        { id: "2-12", title: "Setting Up Foundry for Testing and Deployment" },
        { id: "2-13", title: "Writing Your First Foundry Test Suite" },
        { id: "2-14", title: "Assignment: Multi-Role Access Control System" },
      ],
    },
    {
      id: 3,
      title: "Smart Contract Security Fundamentals",
      subtitle: "Common vulnerabilities, access control, OpenZeppelin",
      icon: "shield",
      lessons: [
        { id: "3-1", title: "The Top 10 Smart Contract Vulnerabilities" },
        { id: "3-2", title: "Reentrancy Attacks: How They Work and How to Stop Them" },
        { id: "3-3", title: "Integer Overflow, Underflow, and Safe Math" },
        { id: "3-4", title: "Front-Running and Transaction Ordering Attacks" },
        { id: "3-5", title: "Denial of Service Patterns in Solidity" },
        { id: "3-6", title: "Access Control with Ownable and Role-Based Patterns" },
        { id: "3-7", title: "Using OpenZeppelin Contracts as Building Blocks" },
        { id: "3-8", title: "Writing Secure Constructors and Initializers" },
        { id: "3-9", title: "The Checks-Effects-Interactions Pattern" },
        { id: "3-10", title: "Pull vs. Push Payment Strategies" },
        { id: "3-11", title: "Audit Checklist: What to Review Before Deploying" },
        { id: "3-12", title: "Assignment: Find and Fix Bugs in a Vulnerable Contract" },
      ],
    },
    {
      id: 4,
      title: "Token Standards",
      subtitle: "ERC-20, ERC-721, ERC-1155, extensions",
      icon: "layers",
      lessons: [
        { id: "4-1", title: "The ERC-20 Standard in Detail" },
        { id: "4-2", title: "Allowance Mechanics and approve/transferFrom" },
        { id: "4-3", title: "Building Mintable and Burnable Tokens" },
        { id: "4-4", title: "ERC-721: Non-Fungible Tokens from First Principles" },
        { id: "4-5", title: "Metadata, Token URIs, and On-Chain vs. Off-Chain Storage" },
        { id: "4-6", title: "ERC-1155: Multi-Token Contracts for Mixed Assets" },
        { id: "4-7", title: "Batch Transfers and Balance Queries in ERC-1155" },
        { id: "4-8", title: "Gas-Efficient Token Design Patterns" },
        { id: "4-9", title: "Storing Files with IPFS and Content Addressing" },
        { id: "4-10", title: "Pinning Services and Decentralized Metadata" },
        { id: "4-11", title: "Building an Upgradeable Token with OpenZeppelin" },
        { id: "4-12", title: "Assignment: Launch an NFT Collection with On-Chain Metadata" },
      ],
    },
    {
      id: 5,
      title: "Frontend Integration & dApp Development",
      subtitle: "React + ethers.js, wallet connections, transaction UX",
      icon: "component",
      lessons: [
        { id: "5-1", title: "How dApps Communicate with the Blockchain" },
        { id: "5-2", title: "Setting Up a React Frontend with ethers.js" },
        { id: "5-3", title: "Connecting Wallets with MetaMask and WalletConnect" },
        { id: "5-4", title: "Reading Contract State from the Frontend" },
        { id: "5-5", title: "Sending Transactions and Handling Confirmations" },
        { id: "5-6", title: "Listening for Events and Updating the UI in Real Time" },
        { id: "5-7", title: "Using Viem as an Alternative to ethers.js" },
        { id: "5-8", title: "Building Responsive dApp Layouts with TailwindCSS" },
        { id: "5-9", title: "Error States, Loading Spinners, and Transaction Toasts" },
        { id: "5-10", title: "Testing Your dApp Against a Local Hardhat Node" },
        { id: "5-11", title: "Assignment: Build a Token Dashboard dApp" },
      ],
    },
    {
      id: 6,
      title: "Advanced Security & Gas Optimization",
      subtitle: "Reentrancy guards, storage packing, MEV awareness",
      icon: "zap",
      lessons: [
        { id: "6-1", title: "Advanced Reentrancy: Cross-Function and Cross-Contract" },
        { id: "6-2", title: "Storage Slot Packing and Layout Optimization" },
        { id: "6-3", title: "Reducing Gas with Immutable and Constant Variables" },
        { id: "6-4", title: "Efficient Data Structures: Bitmaps and Packed Arrays" },
        { id: "6-5", title: "Short-Circuiting and Minimizing External Calls" },
        { id: "6-6", title: "MEV: What Miners Extract and Why It Matters" },
        { id: "6-7", title: "Flashbots, Private Mempools, and MEV Protection" },
        { id: "6-8", title: "Commit-Reveal Schemes to Prevent Front-Running" },
        { id: "6-9", title: "Signature Replay Attacks and Nonce Management" },
        { id: "6-10", title: "Timestamp Dependence and Block Number Manipulation" },
        { id: "6-11", title: "Gas Profiling Your Contracts with Foundry" },
        { id: "6-12", title: "Assignment: Optimize a Gas-Inefficient Protocol" },
      ],
    },
    {
      id: 7,
      title: "DAOs & On-Chain Governance",
      subtitle: "Governance tokens, proposals, voting systems",
      icon: "users",
      lessons: [
        { id: "7-1", title: "What DAOs Are and Why They Exist" },
        { id: "7-2", title: "Governance Tokens and Voting Power" },
        { id: "7-3", title: "Proposal Lifecycle: Creation, Voting, Execution" },
        { id: "7-4", title: "Building a Governor Contract with OpenZeppelin" },
        { id: "7-5", title: "Timelock Controllers and Execution Delays" },
        { id: "7-6", title: "Off-Chain Voting with Snapshot" },
        { id: "7-7", title: "Quadratic Voting and Vote Delegation" },
        { id: "7-8", title: "Treasury Management in DAOs" },
        { id: "7-9", title: "Real-World DAO Architectures: Compound, Uniswap, ENS" },
        { id: "7-10", title: "Assignment: Deploy a Fully Functional DAO" },
      ],
    },
    {
      id: 8,
      title: "Advanced NFTs & Upgradeable Contracts",
      subtitle: "Dynamic NFTs, staking, proxy patterns",
      icon: "image",
      lessons: [
        { id: "8-1", title: "Dynamic NFTs That Change Over Time" },
        { id: "8-2", title: "On-Chain SVG Generation and Rendering" },
        { id: "8-3", title: "NFT Staking Mechanics and Reward Distribution" },
        { id: "8-4", title: "Crafting Systems: Combining and Transforming Tokens" },
        { id: "8-5", title: "Soulbound Tokens and Non-Transferable Credentials" },
        { id: "8-6", title: "The Proxy Pattern and Why Contracts Need Upgrades" },
        { id: "8-7", title: "Transparent Proxy vs. UUPS Proxy" },
        { id: "8-8", title: "Storage Collisions and How to Avoid Them" },
        { id: "8-9", title: "Diamond Pattern (EIP-2535) for Modular Contracts" },
        { id: "8-10", title: "Deploying and Managing Upgradeable Contracts" },
        { id: "8-11", title: "Assignment: Build an Upgradeable NFT Marketplace" },
      ],
    },
    {
      id: 9,
      title: "DeFi Protocols & Liquidity",
      subtitle: "AMMs, lending pools, yield strategies, flash loans",
      icon: "trending-up",
      lessons: [
        { id: "9-1", title: "How Automated Market Makers Actually Work" },
        { id: "9-2", title: "The Constant Product Formula: x * y = k" },
        { id: "9-3", title: "Building a Minimal AMM from Scratch" },
        { id: "9-4", title: "Impermanent Loss and Liquidity Provider Economics" },
        { id: "9-5", title: "Lending and Borrowing: Aave and Compound Mechanics" },
        { id: "9-6", title: "Collateralization Ratios and Liquidation Engines" },
        { id: "9-7", title: "Flash Loans: Uncollateralized Borrowing in One Transaction" },
        { id: "9-8", title: "Vault Strategies and Yield Aggregation" },
        { id: "9-9", title: "Staking Pools and Reward Token Distribution" },
        { id: "9-10", title: "Yield Farming Mechanics and Token Incentive Design" },
        { id: "9-11", title: "Assignment: Implement a Lending Pool with Liquidations" },
      ],
    },
    {
      id: 10,
      title: "Layer 2 Scaling & Rollups",
      subtitle: "Optimistic rollups, ZK rollups, cross-chain bridges",
      icon: "layers",
      lessons: [
        { id: "10-1", title: "Why Ethereum Needs Scaling Solutions" },
        { id: "10-2", title: "Optimistic Rollups: Optimism and Arbitrum" },
        { id: "10-3", title: "Fraud Proofs and the Challenge Period" },
        { id: "10-4", title: "ZK Rollups: zkSync and StarkNet" },
        { id: "10-5", title: "Validity Proofs vs. Fraud Proofs" },
        { id: "10-6", title: "Deploying Contracts to an L2 Network" },
        { id: "10-7", title: "Cross-Chain Messaging and Bridge Architecture" },
        { id: "10-8", title: "Introduction to Cairo for StarkNet Development" },
        { id: "10-9", title: "L1 vs. L2 Gas Economics and Cost Optimization" },
        { id: "10-10", title: "Assignment: Deploy and Test a Contract on an L2 Testnet" },
      ],
    },
    {
      id: 11,
      title: "Gas Optimization & Yul Assembly",
      subtitle: "EVM opcodes, inline assembly, bytecode analysis",
      icon: "cpu",
      lessons: [
        { id: "11-1", title: "EVM Opcodes and the Execution Stack" },
        { id: "11-2", title: "How the Solidity Compiler Translates to Bytecode" },
        { id: "11-3", title: "Reading and Writing Inline Assembly (Yul)" },
        { id: "11-4", title: "Direct Storage Access with sload and sstore" },
        { id: "11-5", title: "Memory Management in Yul: mload, mstore, and the Free Pointer" },
        { id: "11-6", title: "Efficient Loops and Conditional Branching in Assembly" },
        { id: "11-7", title: "Calldata Decoding Without the ABI Decoder" },
        { id: "11-8", title: "Writing a Minimal Contract Entirely in Yul" },
        { id: "11-9", title: "Reverse Engineering Bytecode Without a Decompiler" },
        { id: "11-10", title: "When to Use Assembly and When to Avoid It" },
        { id: "11-11", title: "Assignment: Rewrite a Solidity Function in Pure Yul" },
      ],
    },
    {
      id: 12,
      title: "Account Abstraction & Meta-Transactions",
      subtitle: "ERC-4337, gasless UX, smart contract wallets",
      icon: "wallet",
      lessons: [
        { id: "12-1", title: "The Problem with Externally Owned Accounts" },
        { id: "12-2", title: "ERC-4337: Account Abstraction Without Protocol Changes" },
        { id: "12-3", title: "User Operations, Bundlers, and Entry Points" },
        { id: "12-4", title: "Building a Smart Contract Wallet" },
        { id: "12-5", title: "Paymasters: Sponsoring Gas for Your Users" },
        { id: "12-6", title: "Meta-Transactions and EIP-2771 Trusted Forwarders" },
        { id: "12-7", title: "Gasless Token Approvals with EIP-2612 Permits" },
        { id: "12-8", title: "Key EIPs: 155, 191, 712, 4337, 7702" },
        { id: "12-9", title: "Security Tradeoffs in Account Abstraction" },
        { id: "12-10", title: "Assignment: Build a Gasless Minting Flow" },
      ],
    },
    {
      id: 13,
      title: "Oracles & Off-Chain Data",
      subtitle: "Chainlink, TWAP, verifiable randomness",
      icon: "link",
      lessons: [
        { id: "13-1", title: "The Oracle Problem: Why Blockchains Cannot Fetch Data" },
        { id: "13-2", title: "Chainlink Price Feeds and Data Freshness" },
        { id: "13-3", title: "Integrating a Price Feed into a Solidity Contract" },
        { id: "13-4", title: "Time-Weighted Average Prices (TWAP) from DEX Pools" },
        { id: "13-5", title: "Chainlink VRF: Provably Fair Randomness On-Chain" },
        { id: "13-6", title: "Chainlink Functions: Running Offchain Computation" },
        { id: "13-7", title: "Oracle Manipulation Attacks and Defenses" },
        { id: "13-8", title: "Building a Contract That Reacts to Real-World Events" },
        { id: "13-9", title: "Assignment: Price-Triggered Automated Vault" },
      ],
    },
    {
      id: 14,
      title: "Static & Dynamic Analysis",
      subtitle: "Slither, Echidna, fuzzing, formal verification",
      icon: "search",
      lessons: [
        { id: "14-1", title: "Why Manual Review Is Not Enough" },
        { id: "14-2", title: "Static Analysis with Slither: Setup and Configuration" },
        { id: "14-3", title: "Reading Slither Reports and Triaging Findings" },
        { id: "14-4", title: "Fuzz Testing with Echidna: Property-Based Testing" },
        { id: "14-5", title: "Writing Effective Invariants for Your Contracts" },
        { id: "14-6", title: "Foundry Fuzz Testing and Differential Testing" },
        { id: "14-7", title: "Symbolic Execution and Formal Verification Basics" },
        { id: "14-8", title: "Simulating Real Exploits in a Test Environment" },
        { id: "14-9", title: "Building a Security Testing Pipeline" },
        { id: "14-10", title: "Assignment: Full Security Audit of a DeFi Contract" },
      ],
    },
    {
      id: 15,
      title: "Ethereum Proof of Stake",
      subtitle: "Validators, staking, DVT, the Beacon Chain",
      icon: "server",
      lessons: [
        { id: "15-1", title: "The Merge: From Proof of Work to Proof of Stake" },
        { id: "15-2", title: "Validator Roles: Proposers, Attesters, and Committees" },
        { id: "15-3", title: "Effective Balance, Rewards, and Slashing" },
        { id: "15-4", title: "Running a Validator Node: Requirements and Risks" },
        { id: "15-5", title: "Distributed Validator Technology (DVT)" },
        { id: "15-6", title: "Liquid Staking Protocols: stETH, rETH, and cbETH" },
        { id: "15-7", title: "The Beacon Chain API and Validator Monitoring" },
        { id: "15-8", title: "Assignment: Analyze Validator Performance Data" },
      ],
    },
    {
      id: 16,
      title: "Restaking & Shared Security",
      subtitle: "EigenLayer, AVS, cryptoeconomic security models",
      icon: "shield",
      lessons: [
        { id: "16-1", title: "What Restaking Is and Why It Exists" },
        { id: "16-2", title: "EigenLayer Architecture and Operator Mechanics" },
        { id: "16-3", title: "Actively Validated Services (AVS) Explained" },
        { id: "16-4", title: "Building and Registering an AVS" },
        { id: "16-5", title: "Cryptoeconomic Security and Slashing Conditions" },
        { id: "16-6", title: "Liquid Restaking Tokens and Capital Efficiency" },
        { id: "16-7", title: "The Risks: Cascading Slashing and Systemic Leverage" },
        { id: "16-8", title: "Assignment: Interact with EigenLayer Contracts on Testnet" },
      ],
    },
  ],
};
